### ISSUE TITLE
Value **12** that appears in script **np_util_tf2.py**

### ISSUE THREAD

**Issue by SagacityPuppy** [HangWu2020/CRA-Net#1]
Hi, thanks for your great work and generous open source, I am interested in the Ritter Bounding Ball in your paper, which may be useful to my project.

But I am confused about a detail in your code, concerning the value **12** that appears in **both lines 40 and 91** of the **np_util_tf2.py** script (code_v2/utils/np_util_tf2.py). Since this value is crucial to the selection of the next Ritter ball center, I would like to ask you the selection principles and mechanism of this value.

Looking forward to your reply, thank you very much!

**Comment by HangWu2020** [comment]
Hi,

Thanks for your interest. In FPS, we need to update an array that records the neareast distances from raw points to sampled points. 12 is the initial value of this array, any value that is larger than the maximum point distances in point cloud will be fine.

I think this value should not affect the FPS output if the first sampled point is fixed (e.g.  change 'key_index = np.random.randint(0, num_pts)' to 'key_index=0').

Actually this code has been created for a long time and I may not remember all details correctly, but hope my explanation helps.

**Comment by SagacityPuppy** [comment]
Thank you very much for your answers. Even though this seems simple to you, I had a hard time figuring it out, so it's very helpful, thanks again!
